[package]
name = "stars"
version = "0.1.0"
edition = "2021"


[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3


[dependencies]
bevy = "0.14.2"

rand = "0.8.5"
